### ISSUE TITLE
Fix linting rules

### ISSUE THREAD

**Issue by taylorn16** [taylorn16/fp-toolkit#18]
Mostly need to add in missing rules like using `const` instead of `function` and a few other stylistic things

**Comment by rmjohnson** [comment]
Would that be https://eslint.org/docs/latest/rules/func-style combined with https://eslint.org/docs/latest/rules/prefer-arrow-callback ?

Are there any others we want to add while we're in there?

**Comment by taylorn16** [comment]
> Are there any others we want to add while we're in there?

Great question. Any others that you think would be valuable?

But yes, `func-style` and `prefer-arrow-callback` seem legit to me.

**Comment by rmjohnson** [comment]
Looks like you already have `@typescript-eslint/recommended`. Should we add [@typescript-eslint/recommended-requiring-type-checking](https://typescript-eslint.io/linting/configs/#recommended-requiring-type-checking) as well?

**Comment by taylorn16** [comment]
Yeah that seems like a good add to me

**Comment by rmjohnson** [comment]
Resolved with #31
