### ISSUE TITLE
Use `// =>` format more consistently in @examples

### ISSUE THREAD

**Issue by taylorn16** [taylorn16/fp-toolkit#22]
I like `// =>` here, should we use it elsewhere?

_Originally posted by @rmjohnson in https://github.com/taylorn16/fp-toolkit/pull/20#discussion_r1134626795_

**Comment by rmjohnson** [comment]
Opened #26 to address this.

**Comment by rmjohnson** [comment]
#26 has been merged, closing this. 😎
